---

- name: Gather facts for gw
  become: no
  delegate_to: localhost
  shell: ansible gw -m setup
  tags:
    - facts

- name: Debug IP of GW
  debug:
    msg: "GW VM has IP {{ hostvars['gw']['ansible_eth1']['ipv4']['address'] }}"
    verbosity: 2
  tags:
    - facts

- name: Configure Proxy Settings
  template:
    src: apt.conf
    dest: /etc/apt/apt.conf
    backup: yes
  tags:
    - apt_conf