---

- name: Install Disk Tools
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - parted
    - xfsprogs
  tags: 
    - disk-tools

- name: Create parition xvdo
  parted:
    device: /dev/xvdi
    number: 1
    state: present
  tags:
    - parted

- name: Create parition xvdj
  parted:
    device: /dev/xvdj
    number: 1
    state: present
  tags:
    - parted

- name: Create parition xvdk
  parted:
    device: /dev/xvdk
    number: 1
    state: present
  tags:
    - parted

- name: Create parition xvdl
  parted:
    device: /dev/xvdl
    number: 1
    state: present
  tags:
    - parted

- name: Create parition xvdm
  parted:
    device: /dev/xvdm
    number: 1
    state: present
  tags:
    - parted

- name: Create filesystem xvdi
  filesystem: 
    fstype: xfs 
    dev: /dev/xvdi1 
    opts: "-i size=1024"
  tags:
    - filesystem

- name: Create filesystem xvdj
  filesystem: 
    fstype: xfs 
    dev: /dev/xvdj1 
    opts: "-i size=1024"
  tags:
    - filesystem

- name: Create filesystem xvdk
  filesystem: 
    fstype: xfs 
    dev: /dev/xvdk1 
    opts: "-i size=1024"
  tags:
    - filesystem

- name: Create filesystem xvdl
  filesystem: 
    fstype: xfs 
    dev: /dev/xvdl1 
    opts: "-i size=1024"
  tags:
    - filesystem

- name: Create filesystem xvdm
  filesystem: 
    fstype: xfs 
    dev: /dev/xvdm1 
    opts: "-i size=1024"
  tags:
    - filesystem

- name: Mount /dev/xvdi1
  mount:
    path: /srv/node/xvdi
    src: /dev/xvdi1
    fstype: xfs
    opts: noatime,nodiratime,nobarrier,logbufs=8,auto
    state: mounted
  tags:
    - mount

- name: Mount /dev/xvdj1
  mount:
    path: /srv/node/xvdj
    src: /dev/xvdj1
    fstype: xfs
    opts: noatime,nodiratime,nobarrier,logbufs=8,auto
    state: mounted
  tags:
    - mount

- name: Mount /dev/xvdk1
  mount:
    path: /srv/node/xvdk
    src: /dev/xvdk1
    fstype: xfs
    opts: noatime,nodiratime,nobarrier,logbufs=8,auto
    state: mounted
  tags:
    - mount

- name: Mount /dev/xvdl1
  mount:
    path: /srv/node/xvdl
    src: /dev/xvdl1
    fstype: xfs
    opts: noatime,nodiratime,nobarrier,logbufs=8,auto
    state: mounted
  tags:
    - mount

- name: Mount /dev/xvdm1
  mount:
    path: /srv/node/xvdm
    src: /dev/xvdm1
    fstype: xfs
    opts: noatime,nodiratime,nobarrier,logbufs=8,auto
    state: mounted
  tags:
    - mount

- name: Sending a status update e-mail
  mail:
    host: '{{ host }}'
    port: '{{ port }}'
    secure:  '{{ secure }}'
    username: '{{ username }}'
    password: '{{ password }}'
    from: '{{ from }}'
    to: '{{ to }}'
    subject: '{{ subject_prefix }} Disks Prepared on {{ ansible_hostname }}'
    body: Disks have been prepared for Swift on {{ ansible_hostname }}
  when: send_mail | bool
  tags:
    - mail