---

# Copies the public key which was generated on deployment host to all other hosts for use by openstack-ansible

- name: Add Authorised Key Root User
  authorized_key: user=root key="{{ lookup('file', 'files/id_rsa.pub') }}"
  tags: 
    - auth_key

- name: Sending a status update e-mail
  mail:
    host: '{{ host }}'
    port: '{{ port }}'
    secure:  '{{ secure }}'
    username: '{{ username }}'
    password: '{{ password }}'
    from: '{{ from }}'
    to: '{{ to }}'
    subject: '{{ subject_prefix }} Key Installed on {{ ansible_hostname }}'
    body: Root key has been installed on {{ ansible_hostname }}
  when: send_mail | bool
  tags:
    - mail


### Optionally add additional keys to nodes
# - name: Add Authorised Key Root User - xxx
#   authorized_key: user=root key="{{ lookup('file', 'files/xxx.pub') }}"
#   tags: auth_key