---

- name: Download Cirros Image
  get_url:
    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    dest: /ansible/
  tags:
    - cirros

- name: Install Cirros Image
  os_image:
    cloud: '{{ my_cloud_name }}'
    endpoint_type: admin
    name: cirros-image
    container_format: bare
    disk_format: qcow2
    state: present
    is_public: yes
    filename: cirros-0.4.0-x86_64-disk.img
    properties:
      cpu_arch: x86_64
      distro: ubuntu
  environment:
    OS_CLIENT_CONFIG_FILE: 'openstack.yaml'
  tags:
    - cirros