---

- os_network:
    cloud: '{{ my_cloud_name }}'
    endpoint_type: admin
    provider_network_type: vxlan
    provider_segmentation_id: 123456
    project: '{{ project_2 }}'
    state: present
    name: Corp
    external: true
    shared: true
  environment:
    OS_CLIENT_CONFIG_FILE: 'openstack.yaml'
  tags:
    - corp

- os_subnet:
    cloud: '{{ my_cloud_name }}'
    endpoint_type: admin
    state: present
    network_name: Corp
    name: Corp-Subnet
    cidr: 192.168.140.0/24
    allocation_pool_start: 192.168.140.1
    allocation_pool_end: 192.168.140.99
    gateway_ip: 192.168.140.254
    dns_nameservers:
       - 8.8.8.8
       - 8.8.4.4
  environment:
    OS_CLIENT_CONFIG_FILE: 'openstack.yaml'
  tags:
    - corp
